stages:
  - build
  - deploy

build-app:
  image: node:10.11-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  tags:
    - docker
  stage: build
  script:
    - npm i
    - npm run build --prod
  artifacts:
    paths:
      - dist/front-end

deploy-app:
  stage: deploy
  tags:
    - bare
  script:
    - ls -l dist