stages:
  - build
  - deploy

build-app:
  image: node:10.11-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  tags:
    - docker
  stage: build
  script:
    - npm i
    - npm run build --prod
  artifacts:
    paths:
      - dist/front-end

deploy-app:
  stage: deploy
  tags:
    - bare
  variables:
    IMAGE_CDN_CLI: "$CI_REGISTRY/gt/static-fs/cli:latest"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker run -v `pwd`/dist/front-end:/dist ${IMAGE_CDN_CLI}
        upload --host frontend-ng-test.nextagilesoft.com --directory /dist -c http://192.168.1.8:7000