app: frontend-ng
config: {}

dependencies: {}

handlers:
  ui:
    file: Dockerfile
    url: /
    liveness: /

environments:
  - name: prod
    domain: frontend-ng.nextagilesoft.com
    repository: git@gitlab.nextagilesoft.com:jviejo/frontend.git#master
    type: Kubernetes
    cluster: animal
